# Generated by Django 4.1.4 on 2022-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_App', '0002_alter_note_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='img',
            field=models.ImageField(default='', upload_to='notes-img'),
        ),
    ]
