# Generated by Django 4.1.4 on 2022-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_App', '0003_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(default='', upload_to='media/notes-img'),
        ),
    ]
