# Generated by Django 4.1.4 on 2022-12-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_App', '0005_alter_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='notes-img/'),
        ),
    ]
