# Generated by Django 4.1.4 on 2022-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_firstname_remove_profile_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userphoto',
            field=models.ImageField(default='', upload_to='profile-img'),
        ),
    ]
